### ISSUE TITLE
mistakes in the dictionary

### ISSUE THREAD

**Issue by thomasgm1971** [mkrnr/plover_regenpfeifer#2]
hi martin, many thanks for your regenpfeifer!!!
but the dictionary is somewhat strange...

the german "den" isnt included. TKEPB yields a "denn".
"PWE/SA\*SA/HREPB": "bezahlen". there are lots of SA\*SA's in the dictionary.
"Traumzahle", the proper "Traumzahlen" isnt there. lots of ...zahle.
"TRAUPL/TKPWA/TKPWE": "Traumgage". Gage is pronounciated as "Gashe"-> "TRAUPL/TKPWA/SHE"

etc etc... what are your future plans with the dictionary? 3 years no commit related to the content. its a lot of manual work, but are you still interested in the whole regenpfeifer project? im not into programming, but would enjoy to collaborate on the dictionary!
wish you a happy weekend, thomas

**Comment by mkrnr** [comment]
Hi Thomas,
you are right, the dictionary is strange. It's generated automatically based on https://github.com/mkrnr/wortformliste which is already not perfect and the rules for generating stokes are also not 100%. See also my blog post from 2019: https://stenoblog.com/working-on-a-german-steno-theory/

Last years I didn't have a lot of time for steno and I was focusing on English steno and fingerspelling but I'd be happy to work more on the German steno theory with you!

The errors with the wrong plurals comes from wortformliste:
```
Traumzahl	sg
Traumzahle	pl
```
We could start there and try to improve this list if you're interested. You can find my email in my github profile so that we can get in contact directly.

Best,
Martin
